version: '3'

services:
  scimgateway:
    build: ./scimgateway
    ports:
      - "8880:8880"
    restart: always
    environment:
      loki-new-connector_OAUTH2_0_CLIENT_ID: wagner
      loki-new-connector_OAUTH2_0_CLIENT_SECRET: 54545

    volumes:
      - data:/home/node/app/data
   
  forms:
    depends_on:
      - scimgateway
    build: ./forms
    ports:
      - "8000:80"
    restart: always
  
     

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/wagner/Documents/qscim-files/temp/data